included:
  - Attribution
excluded:
  - Pods
  - .build

disabled_rules:
  - trailing_whitespace
  - vertical_parameter_alignment
  - nesting
  - implicit_return
  - multiline_parameters_brackets
  - multiline_function_chains

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - redundant_nil_coalescing
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - fatal_error_message
  - pattern_matching_keywords
  - array_init
  - contains_over_first_not_nil
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - unneeded_break_in_switch
  - sorted_first_last
  - trailing_closure
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

analyzer_rules:
  - unused_import

# Customized rules
line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length: 2 # Allow shorter names like 'ip'
  max_length: 40

function_parameter_count:
  warning: 6
  error: 8
