included:
  - Attribution
excluded:
  - Pods
  - .build

# Rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - unused_import
  - redundant_nil_coalescing
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - fatal_error_message
  - joined_default_parameter
  - pattern_matching_keywords
  - array_init
  - contains_over_first_not_nil
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - implicit_return
  - unneeded_break_in_switch
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - redundant_type_annotation
  - strict_fileprivate
  - sorted_first_last
  - trailing_closure
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Customized rules
line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

function_body_length:
  warning: 50
  error: 100
