name: Publish to CocoaPods

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Deploy to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod spec lint ReddimonAttribution.podspec
          pod trunk push ReddimonAttribution.podspec
